// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"github.com/bitrise-io/bitrise-oauth/service"
	"net/http"
	"sync"
)

// Ensure, that JwtValidatorRepositoryMock does implement service.JwtValidatorRepository.
// If this is not the case, regenerate this file with moq.
var _ service.JwtValidatorRepository = &JwtValidatorRepositoryMock{}

// JwtValidatorRepositoryMock is a mock implementation of service.JwtValidatorRepository.
//
//	func TestSomethingThatUsesJwtValidatorRepository(t *testing.T) {
//
//		// make and configure a mocked service.JwtValidatorRepository
//		mockedJwtValidatorRepository := &JwtValidatorRepositoryMock{
//			GetJwtValidatorForRawTokenFunc: func(rawJwt string) (service.Validator, string, error) {
//				panic("mock out the GetJwtValidatorForRawToken method")
//			},
//			GetJwtValidatorForRequestFunc: func(r *http.Request) (service.Validator, string, error) {
//				panic("mock out the GetJwtValidatorForRequest method")
//			},
//		}
//
//		// use mockedJwtValidatorRepository in code that requires service.JwtValidatorRepository
//		// and then make assertions.
//
//	}
type JwtValidatorRepositoryMock struct {
	// GetJwtValidatorForRawTokenFunc mocks the GetJwtValidatorForRawToken method.
	GetJwtValidatorForRawTokenFunc func(rawJwt string) (service.Validator, string, error)

	// GetJwtValidatorForRequestFunc mocks the GetJwtValidatorForRequest method.
	GetJwtValidatorForRequestFunc func(r *http.Request) (service.Validator, string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetJwtValidatorForRawToken holds details about calls to the GetJwtValidatorForRawToken method.
		GetJwtValidatorForRawToken []struct {
			// RawJwt is the rawJwt argument value.
			RawJwt string
		}
		// GetJwtValidatorForRequest holds details about calls to the GetJwtValidatorForRequest method.
		GetJwtValidatorForRequest []struct {
			// R is the r argument value.
			R *http.Request
		}
	}
	lockGetJwtValidatorForRawToken sync.RWMutex
	lockGetJwtValidatorForRequest  sync.RWMutex
}

// GetJwtValidatorForRawToken calls GetJwtValidatorForRawTokenFunc.
func (mock *JwtValidatorRepositoryMock) GetJwtValidatorForRawToken(rawJwt string) (service.Validator, string, error) {
	if mock.GetJwtValidatorForRawTokenFunc == nil {
		panic("JwtValidatorRepositoryMock.GetJwtValidatorForRawTokenFunc: method is nil but JwtValidatorRepository.GetJwtValidatorForRawToken was just called")
	}
	callInfo := struct {
		RawJwt string
	}{
		RawJwt: rawJwt,
	}
	mock.lockGetJwtValidatorForRawToken.Lock()
	mock.calls.GetJwtValidatorForRawToken = append(mock.calls.GetJwtValidatorForRawToken, callInfo)
	mock.lockGetJwtValidatorForRawToken.Unlock()
	return mock.GetJwtValidatorForRawTokenFunc(rawJwt)
}

// GetJwtValidatorForRawTokenCalls gets all the calls that were made to GetJwtValidatorForRawToken.
// Check the length with:
//
//	len(mockedJwtValidatorRepository.GetJwtValidatorForRawTokenCalls())
func (mock *JwtValidatorRepositoryMock) GetJwtValidatorForRawTokenCalls() []struct {
	RawJwt string
} {
	var calls []struct {
		RawJwt string
	}
	mock.lockGetJwtValidatorForRawToken.RLock()
	calls = mock.calls.GetJwtValidatorForRawToken
	mock.lockGetJwtValidatorForRawToken.RUnlock()
	return calls
}

// GetJwtValidatorForRequest calls GetJwtValidatorForRequestFunc.
func (mock *JwtValidatorRepositoryMock) GetJwtValidatorForRequest(r *http.Request) (service.Validator, string, error) {
	if mock.GetJwtValidatorForRequestFunc == nil {
		panic("JwtValidatorRepositoryMock.GetJwtValidatorForRequestFunc: method is nil but JwtValidatorRepository.GetJwtValidatorForRequest was just called")
	}
	callInfo := struct {
		R *http.Request
	}{
		R: r,
	}
	mock.lockGetJwtValidatorForRequest.Lock()
	mock.calls.GetJwtValidatorForRequest = append(mock.calls.GetJwtValidatorForRequest, callInfo)
	mock.lockGetJwtValidatorForRequest.Unlock()
	return mock.GetJwtValidatorForRequestFunc(r)
}

// GetJwtValidatorForRequestCalls gets all the calls that were made to GetJwtValidatorForRequest.
// Check the length with:
//
//	len(mockedJwtValidatorRepository.GetJwtValidatorForRequestCalls())
func (mock *JwtValidatorRepositoryMock) GetJwtValidatorForRequestCalls() []struct {
	R *http.Request
} {
	var calls []struct {
		R *http.Request
	}
	mock.lockGetJwtValidatorForRequest.RLock()
	calls = mock.calls.GetJwtValidatorForRequest
	mock.lockGetJwtValidatorForRequest.RUnlock()
	return calls
}
